### Get all Books
GET http://localhost:3000/api/books HTTP/1.1


### Create a new Book
POST http://localhost:3000/api/books HTTP/1.1
Content-Type: application/json

{
    "title": "New Book",
    "author": "John Doe",
    "genra": "Fiction",
    "year": 2023
}

### Delete a Book
DELETE http://localhost:3000/api/books/asd  HTTP/1.1
`Content-Type: application/json

### Patch a Book
PATCH http://localhost:3000/api/books/88a73e24-c2f2-4dd0-b7bf-16c0c18076a1 HTTP/1.1
Content-Type: application/json

{
    "title": "RANDELL BOOK"
}


### Get all Users
GET http://localhost:3000/api/users HTTP/1.1

### Create a new User
POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQzMjhhNDkzLTVlZTAtNGFmMi1hZWVlLWVmMmE5M2ExOWMyNyIsIm5hbWUiOiJSYW5kZWxsIiwiZW1haWwiOiJkZXZAZ21haWwuY29tIiwiaWF0IjoxNzUxNTkxMjI2LCJleHAiOjE3NTE1OTEyNTZ9.GRaoAg1A4aOsqr2UUjGcGS2WQh1z4_faHHlW7te0TC8
{
    "name": "Randell",
    "email": "dev1@gmail.com",
    "pwd": "Sample123"
}

### Delete a User
DELETE http://localhost:3000/api/users/8f7063da-ce7d-4f583cb-42ff60443b56 HTTP/1.1
Content-Type: application/json


### Authenticate a User
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "dev@gmail.com",
    "pwd": "Sample123"
}


### Use the accessToken from the previous response
GET http://localhost:3000/api/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQzMjhhNDkzLTVlZTAtNGFmMi1hZWVlLWVmMmE5M2ExOWMyNyIsIm5hbWUiOiJSYW5kZWxsIiwiZW1haWwiOiJkZXZAZ21haWwuY29tIiwiaWF0IjoxNzUxNTkzOTUzLCJleHAiOjE3NTE1OTUxNTN9.cQcFecGdezgF_ah3viYdgSdoRIEbMpngtcvb19aGp7M